### ISSUE TITLE
Introduce Murmur personality

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/grumble#24]
It would be nice if grumble could be used *exactly* like Murmur.

Things like these would be needed for that to happen:
- [ ] https://github.com/mumble-voip/grumble/issues/21 - Introduce compatibility with Murmur .ini files
- [ ] https://github.com/mumble-voip/grumble/issues/22 - Introduce compatibility with Murmur SQL databases
- [ ] https://github.com/mumble-voip/grumble/issues/23 - Introduce compatibility with Murmur's gRPC interface
